USE DziejeSieApp
CREATE TABLE dbo.Events(
EventId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Name VARCHAR(MAX) NOT NULL,
Address VARCHAR(MAX) NOT NULL,
PostCode VARCHAR(6) CHECK (PostCode LIKE '[0-9][0-9]-[0-9][0-9][0-9]%') NOT NULL,
Town VARCHAR(MAX) NOT NULL,
EventDate DATETIME NOT NULL,
UserId INT NOT NULL,
DateAdd DATETIME NOT NULL,

CONSTRAINT FKIdUserEventAdd FOREIGN KEY(UserId) REFERENCES Users(UserId)
)